### ISSUE TITLE
Driver Leftovers.xml - Windows

### ISSUE THREAD

**Issue by Chaython** [bleachbit/cleanerml#275]
A cleanerml xml to delete AMD/Nvidia and other driver installation media.

Each option will save users several hundred mb to several gigabytes in space, depending on how many drivers they have installed, and the last time they deleted the dirs.

https://github.com/bleachbit/cleanerml/pull/274

**Comment by az0** [comment]
Because there is already a pull request 274, are you okay closing this issue 275?

**Comment by Chaython** [comment]
I found it to be nonsensical, however the doccumentation says "Submit the cleaner to cleanerml on GitHub as an issue (with a link to a gist) or pull request." So I made a pull request then an issue, with the link to the pull request.
