### ISSUE TITLE
Cleanup of all Windows User Profiles possible? 

### ISSUE THREAD

**Issue by kurzpc** [bleachbit/cleanerml#279]
Hello,

does BleachBit only clean up the user profile of the current user? 
Or also all other user profiles that exist on the PC?

**Comment by az0** [comment]
Just the current user, but I agree cleaning other user profiles would be useful. It's filed here https://github.com/bleachbit/wishlist/issues/80

Would you rather select a list of user profiles or enable a single option to clean them all? Are you on Windows or Linux?

**Comment by kurzpc** [comment]
A simple enable diabel switch would be sufficient. 
For Windows Terminal Server this option would be very good.

**Comment by kurzpc** [comment]
> 
> 
> Just the current user, but I agree cleaning other user profiles would be useful. It's filed here [bleachbit/wishlist#80](https://github.com/bleachbit/wishlist/issues/80)
> 
> Would you rather select a list of user profiles or enable a single option to clean them all? Are you on Windows or Linux?

A simple enable diabel switch would be sufficient. 
For Windows Terminal Server this option would be very good.
