### ISSUE TITLE
New CleanerML file for Heroes of the Storm

### ISSUE THREAD

**Issue by Nightblade** [bleachbit/cleanerml#293]
https://gist.github.com/Nightblade/a55a675421c2be037600809f723e02af

Do I need to request testing?

I couldn't find a clean way of referring/linking to a Gist here sorry.

**Comment by az0** [comment]
Thanks. 

BTW

1.  The preferred method is through a pull request. 
2. I made this change https://github.com/bleachbit/cleanerml/commit/d4edf35a3e205d43de1a2b349696c881f0e66a00

**Comment by Nightblade** [comment]
Noted!  I did try to make PR first, but I couldn't work out how to reference a Gist.

**Comment by az0** [comment]
The pull request is in place of the gist. The gist isn't involved with the pull request

**Comment by Nightblade** [comment]
Ah ok.  You might want to update the documentation then:

> Submit the cleaner to [cleanerml on GitHub](https://github.com/bleachbit/cleanerml) as an issue (with a link to a gist) or pull request.

https://docs.bleachbit.org/cml/contributing.html
