### ISSUE TITLE
Correct %WinDir%\System32\config\Systemprofile\AppData\Local\Microsoft\Windows\INetCache\

### ISSUE THREAD

**Issue by elgatov** [bleachbit/cleanerml#297]
Hi,

I believe 
`%WinDir%\System32\config\Systemprofile\AppData\Local\Microsoft\Windows\INetCache\`, should be corrected to:
`%WinDir%\System32\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\`. 

When I changed it in my `internet_explorer.xml`, bleachbit was able to find the folder and clean it.

Regards.

**Comment by az0** [comment]
The case of the directory does not make a difference to Windows, but the problem here is that BleachBit as a 32-process is affected by the [file system redirector](https://learn.microsoft.com/en-us/windows/win32/winprog64/file-system-redirector).
